---
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: page
- name: show-avatar
  label: Show avatar
  type: boolean
  hidden: false
  default: true
pages:
- scom-planning.md
- system-center-operations-manager.md
